spring.datasource.url=jdbc:postgresql://localhost:5432/gymcrm_stg
spring.datasource.username=${STG_DB_USERNAME}
spring.datasource.password=${STG_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
