CREATE TABLE trainer_monthly_workload (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      trainer_username VARCHAR(100) NOT NULL,
      trainer_first_name VARCHAR(100) NOT NULL,
      trainer_last_name VARCHAR(100) NOT NULL,
      trainer_active BOOLEAN NOT NULL,

      workload_year INTEGER NOT NULL,
      workload_month INTEGER NOT NULL,

      training_duration_minutes BIGINT NOT NULL DEFAULT 0,
      version BIGINT NOT NULL DEFAULT 0,

      CONSTRAINT uk_trainer_workload_username_year_month
          UNIQUE (trainer_username, workload_year, workload_month),

      CONSTRAINT ck_trainer_workload_month
          CHECK (workload_month BETWEEN 1 AND 12),

      CONSTRAINT ck_trainer_workload_duration
          CHECK (training_duration_minutes >= 0)
);

CREATE INDEX idx_trainer_workload_username
    ON trainer_monthly_workload (trainer_username);

CREATE INDEX idx_trainer_workload_year_month
    ON trainer_monthly_workload (workload_year, workload_month);